function gmdl = geomModelPrep(mp)

% mp = mPara32(mp.thorH);
%%
hrt = strcat(' solid hrt =',...
 'sphere(',...
  string(mp.norm.heart.offsetX),',',...
  string(mp.norm.heart.offsetY),',',...
  string(mp.norm.heart.offsetZ),';',...
  string(mp.norm.heart.R),...
');');

lLung = strcat(' solid lLung =',...
' ellipsoid(',...
  string(mp.norm.lung.left.offsetX),',',...
  string(mp.norm.lung.left.offsetY),',',...
  string(mp.norm.lung.left.offsetZ),';',...
  string(mp.norm.lung.left.Wdth),',',...
  string(0),',',...
  string(0),';',...
  string(0),',',...
  string(mp.norm.lung.left.Wdth),',',...
  string(0),';',...
  string(0),',',...
  string(0),',',...
  string(mp.norm.lung.left.H),...
');');

rLung = strcat(' solid rLung =',...
' ellipsoid(',...
  string(mp.norm.lung.right.offsetX),',',...
  string(mp.norm.lung.right.offsetY),',',...
  string(mp.norm.lung.right.offsetZ),';',...
  string(mp.norm.lung.right.Wdth),',',...
  string(0),',',...
  string(0),';',...
  string(0),',',...
  string(mp.norm.lung.right.Wdth),',',...
  string(0),';',...
  string(0),',',...
  string(0),',',...
  string(mp.norm.lung.right.H),...
');');

extra={'hrt','lLung','rLung',[hrt,lLung,rLung]};
%%
gmdl = ng_mk_cyl_models([mp.norm.thorH,...
                        [mp.norm.thorR,...
                        0.1]],...
                          [mp.elecLast, mp.norm.beltH + mp.norm.thorH/2],...
                            [mp.norm.elecRad],extra); 
end
