%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\OneDrive\bmstu\!! Master's thesis\00 03 thesis\comsol_fullcircle\inj01_02.txt
%
% Auto-generated by MATLAB on 11-Jan-2020 13:53:17

startElectrode = 01;
endElectrode   = 32;
thoraxRadious = 0.315; %mm

comsolData = cell(2 ,endElectrode);
dir = "D:\OneDrive\bmstu\!! Master's thesis\00 03 thesis\comsol_fullcircle\data\inj";
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [10, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["x", "y", "z", "phi", "Jx", "Jy", "Jz"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

%% Iterative import

for j = startElectrode:1:endElectrode
  electrodePos = j;
    if j == endElectrode
      electrodeNeg = startElectrode;
    else
      electrodeNeg = j+1;
    end
    
    if j < 9
      filename = strcat(dir, "0", string(electrodePos), "_0", string(electrodeNeg));
    elseif j == 9
      filename = strcat(dir, "0", string(electrodePos), "_", string(electrodeNeg));
    else
      filename = strcat(dir, string(electrodePos), "_", string(electrodeNeg));
    end 
  comsolData{2,j} = readtable(filename, opts);
  comsolData{1,j} = strcat('pos',string(electrodePos), '_neg',string(electrodeNeg));
end
% Import the data
%%

clear opts j filename electrodeNeg electrodePos dir 