clear extra
clear fmdl
close
mParam = mPara(1);
mParam = mPara(mParam.thorH);
run C:\eidors-v3.10-ng\eidors\startup.m
%%
hrt = strcat(' solid hrt =',...
 'sphere(',...
  string(mParam.norm.heart.offsetX),',',...
  string(mParam.norm.heart.offsetY),',',...
  string(mParam.norm.heart.offsetZ),';',...
  string(mParam.norm.heart.R),...
');');

lLung = strcat(' solid lLung =',...
' ellipsoid(',...
  string(mParam.norm.lung.left.offsetX),',',...
  string(mParam.norm.lung.left.offsetY),',',...
  string(mParam.norm.lung.left.offsetZ),';',...
  string(mParam.norm.lung.left.Wdth),',',...
  string(0),',',...
  string(0),';',...
  string(0),',',...
  string(mParam.norm.lung.left.Wdth),',',...
  string(0),';',...
  string(0),',',...
  string(0),',',...
  string(mParam.norm.lung.left.H),...
');');

rLung = strcat(' solid rLung =',...
' ellipsoid(',...
  string(mParam.norm.lung.right.offsetX),',',...
  string(mParam.norm.lung.right.offsetY),',',...
  string(mParam.norm.lung.right.offsetZ),';',...
  string(mParam.norm.lung.right.Wdth),',',...
  string(0),',',...
  string(0),';',...
  string(0),',',...
  string(mParam.norm.lung.right.Wdth),',',...
  string(0),';',...
  string(0),',',...
  string(0),',',...
  string(mParam.norm.lung.right.H),...
');');

extra={'hrt','lLung','rLung',[hrt,lLung,rLung]};
%%
clear fmdl hrt lLung rLung
